# Generated by Django 4.2.2 on 2023-10-11 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='music_uploads_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('music_name', models.CharField(max_length=400)),
                ('music_file', models.FileField(upload_to='music/')),
                ('music_type', models.CharField(max_length=10)),
                ('music_genre', models.CharField(choices=[('disco', 'Disco'), ('funk', 'Funk'), ('rock', 'Rock'), ('blues', 'Blues'), ('rapping', 'Rapping')], max_length=10)),
                ('owner_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='protected_accessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_platform.music_uploads_model')),
            ],
            options={
                'unique_together': {('music_id', 'email')},
            },
        ),
    ]
