# Generated by Django 4.2.2 on 2023-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0003_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
