# Generated by Django 4.2.2 on 2023-11-26 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0004_alter_custom_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='music_platform.artists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
