# Generated by Django 4.2.2 on 2023-11-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0005_userclicks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclicks',
            unique_together={('user', 'artist')},
        ),
    ]
