# Generated by Django 4.2.4 on 2023-11-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0006_alter_userclicks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclicks',
            unique_together=set(),
        ),
    ]
